// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config } from "dotenv"
import { defineConfig } from "prisma/config"

// Load .env.local first, then .env as fallback
config({ path: ".env.local" })
config({ path: ".env" })

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Migrate/introspect should always go through the direct (non-pooled)
    // connection, since pgbouncer's transaction pooling doesn't release
    // Prisma's session-level advisory lock cleanly. Falls back to
    // DATABASE_URL if DIRECT_URL isn't set (e.g. non-pooled local Postgres).
    url:
      process.env.DIRECT_URL ||
      process.env.DATABASE_URL ||
      "postgresql://localhost:5432/fantasyphish",
  },
})
